// tests/e2e-prod/all-tools-execution.spec.ts
//
// 2026-06-03 — COMPREHENSIVE per-tool execution. One test per tool
// across the WHOLE catalog (tests/e2e-prod/tool-manifest.json — 113
// tools: 60 free + 53 AI), full output verification. Goal: prove every
// tool actually RUNS end-to-end against production — "no gaps".
//
// Strategy (generic, manifest-driven — no per-tool hand-coding):
//   1. Navigate /tool/<id>.
//   2. Upload the right fixture(s) into EVERY visible file input,
//      chosen by each input's `accept` attribute (PDF / image / text
//      / csv). 2-input tools (pdf-diff, pdf-overlay, image-watermark,
//      ai-compare) get each slot its matching fixture automatically.
//   3. Fill any empty visible textarea / required text field with a
//      sample string (covers prompt tools: ai-generate, ai-jd-match,
//      ai-cover-letter).
//   4. Click the primary action button (best-effort verb match;
//      many tools auto-run on upload).
//   5. SUCCESS = download affordance appears OR output/result/preview
//      region populates OR a benign "nothing found" message OR (AI) an
//      /api/ai/* POST returns <400 / 402. FAILURE = a visible ERROR
//      alert, or a hard timeout with no signal (surfaced as a gap to
//      triage).
//
// Free tools: client-side, no auth, no cost. AI tools: require login +
// consume credits; gated on PROD_E2E_TEST_* + PROD_E2E_AI_BUDGET_OK,
// and tolerate 402 (out-of-credits guardrail) as a non-failure.
//
// Fixtures come from tests/fixtures/ (regenerated by
// tests/fixtures/generate-all.mjs in the workflow before this runs).

import { test, expect, type Page } from "@playwright/test";
import { resolve } from "node:path";
import { readFileSync } from "node:fs";

const FX = (n: string) => resolve(process.cwd(), "tests", "fixtures", n);
const PDF = FX("multi-page.pdf");
const PDF2 = FX("single-page.pdf");
const IMG_PNG = FX("sample.png");
const IMG_JPG = FX("sample.jpg");
const TXT = FX("sample.txt");
const CSV = FX("sample.csv");
const MD = FX("sample.md");

type ToolRow = { id: string; name: string; free: boolean; group: string; needsAuth: boolean; special: string };
const MANIFEST: ToolRow[] = JSON.parse(readFileSync(resolve(process.cwd(), "tests", "e2e-prod", "tool-manifest.json"), "utf8"));
const FREE = MANIFEST.filter((t) => t.free);
const AI = MANIFEST.filter((t) => !t.free);

const EMAIL = process.env.PROD_E2E_TEST_EMAIL;
const PASSWORD = process.env.PROD_E2E_TEST_PASSWORD;
const AI_OK = process.env.PROD_E2E_AI_BUDGET_OK === "yes";

// ---- generic drivers -------------------------------------------------

// Feed each visible file input the fixture its `accept` attr asks for.
async function uploadByAccept(page: Page): Promise<number> {
  const inputs = page.locator('input[type="file"]');
  const n = await inputs.count();
  let fed = 0;
  for (let i = 0; i < n; i++) {
    const inp = inputs.nth(i);
    // skip inputs that are detached / already consumed
    if ((await inp.count()) === 0) continue;
    const accept = ((await inp.getAttribute("accept")) || "").toLowerCase();
    const multiple = (await inp.getAttribute("multiple")) !== null;
    let files: string[];
    if (/image|png|jpe?g/.test(accept) && !/pdf/.test(accept)) {
      files = /png/.test(accept) && !/jpe?g/.test(accept) ? [IMG_PNG] : [IMG_JPG];
    } else if (/csv|tsv/.test(accept) && !/pdf/.test(accept)) {
      files = [CSV];
    } else if (/(text|\.txt|markdown|\.md)/.test(accept) && !/pdf/.test(accept)) {
      files = /md|markdown/.test(accept) ? [MD] : [TXT];
    } else {
      files = multiple ? [PDF, PDF2] : [PDF];
    }
    try {
      await inp.setInputFiles(files, { timeout: 8000 });
      fed++;
      await page.waitForTimeout(400); // let the dropzone react / reveal slot 2
    } catch {
      /* input may have been replaced by a chip after a sibling upload */
    }
  }
  return fed;
}

// Fill empty visible textareas + obvious prompt text fields.
async function fillTextInputs(page: Page): Promise<void> {
  const tas = page.locator("textarea:visible");
  const n = await tas.count();
  for (let i = 0; i < n; i++) {
    const ta = tas.nth(i);
    if ((await ta.inputValue()) === "") {
      try { await ta.fill("pdfcraftai automated end-to-end verification. Please process this sample input and produce a result."); } catch { /* readonly */ }
    }
  }
  // a title-ish text input (ai-generate has a title field)
  const title = page.getByPlaceholder(/title|Q3 Product Launch Brief|name of/i).first();
  if ((await title.count()) > 0) { try { await title.fill("E2E verification"); } catch { /* */ } }
}

const ACTION = /summari[sz]e|simplif|explain|extract|generate|\brun\b|^apply$|review|improve|audit|translate|rewrite|convert|analy[sz]e|detect|proofread|paraphrase|condense|expand|^create|build|make|process|^start$|fill|\bsign\b|redact|compare|parse|match|table|map|quiz|flash ?card|study notes|brief|draft|stamp|watermark|merge|split|rotate|number|booklet|crop|resize|overlay|highlight|outline|repair|flatten|strip|grayscale|bates|odd|even|n-?up|sort|delete pages|unlock|count|inspect|search|to (text|markdown|html|jpe?g|png|pdf|grayscale)/i;
const NOT_ACTION = /sign ?in|log ?in|sign ?up|register|google|reset|clear|cancel|remove|back|upgrade|buy|pricing|menu|close|new chat|learn more|how it works|download|copy|sample|feedback|report|share/i;

// Click the best-guess primary action (best-effort; ok if none/fails).
async function clickPrimaryAction(page: Page): Promise<void> {
  const buttons = page.locator("button:visible, a[role=button]:visible");
  const n = await buttons.count();
  for (let i = 0; i < n; i++) {
    const b = buttons.nth(i);
    const name = ((await b.textContent()) || "").trim();
    if (!name || NOT_ACTION.test(name) || !ACTION.test(name)) continue;
    if (!(await b.isEnabled())) continue;
    try { await b.click({ timeout: 4000 }); return; } catch { /* try next */ }
  }
  // Fallback: the design system renders every primary CTA as
  // `button.btn-primary`. Click the first visible+enabled one that
  // isn't an obvious non-action (upgrade/sign-in/etc.).
  const primaries = page.locator("button.btn-primary:visible");
  const pn = await primaries.count();
  for (let i = 0; i < pn; i++) {
    const b = primaries.nth(i);
    const name = ((await b.textContent()) || "").trim();
    if (NOT_ACTION.test(name)) continue;
    if (!(await b.isEnabled())) continue;
    try { await b.click({ timeout: 4000 }); return; } catch { /* try next */ }
  }
}

const ERROR_RX = /\b(error|failed|couldn.?t|could not|unable|invalid|not a valid|something went wrong|unsupported|too large|went wrong)\b/i;
const BENIGN_EMPTY_RX = /\bno (images|attachments|links|form fields|fields|fonts|annotations|javascript|bookmarks|metadata|results|matches|tables|dates|contacts|outline)\b/i;

// Wait for a client-side success signal vs an error. Returns a verdict.
async function awaitClientVerdict(page: Page, ms = 25_000): Promise<{ ok: boolean; reason: string }> {
  const deadline = Date.now() + ms;
  while (Date.now() < deadline) {
    // hard error alert?
    const alerts = page.locator('[role="alert"]:visible, .error:visible, [data-error]:visible');
    const an = await alerts.count();
    for (let i = 0; i < an; i++) {
      const t = ((await alerts.nth(i).textContent()) || "").trim();
      if (t && ERROR_RX.test(t) && !BENIGN_EMPTY_RX.test(t)) return { ok: false, reason: `error alert: ${t.slice(0, 120)}` };
    }
    // success affordances
    const dl = page.locator('a[download]:visible, button:visible:has-text("Download")');
    if ((await dl.count()) > 0) {
      for (let i = 0; i < (await dl.count()); i++) { if (await dl.nth(i).isEnabled().catch(() => false)) return { ok: true, reason: "download affordance" }; }
    }
    const out = page.locator('[data-testid*="output"]:visible, [data-testid*="result"]:visible, pre:visible, table:visible, canvas:visible');
    if ((await out.count()) > 0) return { ok: true, reason: "output region rendered" };
    // benign-empty valid result
    const body = ((await page.locator("main").first().textContent().catch(() => "")) || "");
    if (BENIGN_EMPTY_RX.test(body)) return { ok: true, reason: "valid empty result" };
    await page.waitForTimeout(700);
  }
  return { ok: false, reason: "no success/error signal within timeout (needs manual check)" };
}

// ---- FREE tools ------------------------------------------------------

test.describe("free tool execution (all)", () => {
  test.describe.configure({ retries: 1 });
  for (const tool of FREE) {
    test(`free:${tool.id} — ${tool.name}`, async ({ page }) => {
      test.setTimeout(60_000);
      const resp = await page.goto(`/tool/${tool.id}`, { waitUntil: "domcontentloaded" });
      expect(resp?.status() ?? 0, "page should load <400").toBeLessThan(400);
      // mount: a file input OR a textarea OR a runnable control should exist
      await page.waitForTimeout(800);
      const fed = await uploadByAccept(page);
      await fillTextInputs(page);
      if (fed > 0 || (await page.locator("textarea:visible").count()) > 0) {
        await clickPrimaryAction(page);
        const v = await awaitClientVerdict(page);
        test.info().annotations.push({ type: "verdict", description: `${tool.id}: ${v.reason}` });
        expect(v.ok, `${tool.id}: ${v.reason}`).toBe(true);
      } else {
        // no input affordance at all = the runner failed to mount its UI
        expect(false, `${tool.id}: no file input or textarea found (runner mount gap)`).toBe(true);
      }
    });
  }
});

// ---- AI tools --------------------------------------------------------

async function login(page: Page) {
  await page.goto("/login");
  await page.locator('input[type="email"]').fill(EMAIL!);
  await page.locator('input[type="password"]').fill(PASSWORD!);
  await page.getByRole("button", { name: /sign in|log in/i }).click();
  await expect(page).toHaveURL(/\/app\//, { timeout: 20_000 });
}

test.describe("AI tool execution (all)", () => {
  test.describe.configure({ mode: "serial" });
  test.skip(!EMAIL || !PASSWORD, "AI: PROD_E2E_TEST_EMAIL/PASSWORD unset");
  test.skip(!AI_OK, "AI: PROD_E2E_AI_BUDGET_OK!=yes (each run spends credits)");

  test.beforeEach(async ({ page }) => { await login(page); });

  for (const tool of AI) {
    test(`ai:${tool.id} — ${tool.name}`, async ({ page }) => {
      test.setTimeout(120_000);

      if (tool.special === "chat") {
        // multi-turn chat lives at /app/chat
        await page.goto("/app/chat");
        await Promise.all([
          page.waitForURL(/\/app\/chat\/[A-Za-z0-9-]{6,}/, { timeout: 25_000 }),
          page.getByRole("button", { name: /^New chat$/ }).first().click(),
        ]);
        const input = page.getByPlaceholder(/Ask a question/i);
        await input.fill("Say hello in one sentence.");
        const [status] = await Promise.all([
          page.waitForResponse((r) => /\/api\/ai\/chat/.test(r.url()) && r.request().method() === "POST", { timeout: 90_000 }).then((r) => r.status()),
          page.getByRole("button", { name: /^Send$/ }).first().click(),
        ]);
        if (status === 402) { test.info().annotations.push({ type: "ai-402", description: "out of credits" }); return; }
        expect(status, "chat route <400").toBeLessThan(400);
        return;
      }

      const resp = await page.goto(`/tool/${tool.id}`, { waitUntil: "domcontentloaded" });
      expect(resp?.status() ?? 0, "page <400").toBeLessThan(400);
      await page.waitForTimeout(800);
      if (tool.special !== "prompt") await uploadByAccept(page);
      await fillTextInputs(page);

      // Race: an /api/ai/* POST fires (authoritative) vs a click that
      // triggers it. Install the listener before clicking.
      const aiResp = page.waitForResponse(
        (r) => /\/api\/ai\//.test(r.url()) && r.request().method() === "POST",
        { timeout: 95_000 },
      ).then((r) => r.status()).catch(() => -1);
      await clickPrimaryAction(page);
      const status = await aiResp;

      if (status === -1) {
        // No AI call fired — maybe the button needs a different label,
        // or a required field was missing. Surface as a gap to triage.
        // Fall back: did the UI at least render an output (some AI tools
        // stream into a region without a classic POST we matched)?
        const v = await awaitClientVerdict(page, 8000);
        test.info().annotations.push({ type: "verdict", description: `${tool.id}: no /api/ai POST; client=${v.reason}` });
        expect(v.ok, `${tool.id}: no /api/ai/* POST fired and no output region (needs manual check)`).toBe(true);
        return;
      }
      if (status === 402) { test.info().annotations.push({ type: "ai-402", description: `${tool.id}: out of credits` }); return; }
      expect(status, `${tool.id}: AI route <400 (or 402)`).toBeLessThan(400);
    });
  }
});
