// tests/e2e/ai-summarize.spec.ts
//
// E2E for /tool/ai-summarize — exercises the AI tool flow with the
// /api/ai/summarize route mocked. The mock keeps the test hermetic
// (no real LLM call, no $ cost, no rate-limit risk, deterministic
// output) while still verifying the user-visible flow:
//   upload → click Run → loading state → mocked response renders.
//
// Auth: AI op routes are gated. For the scaffold we mock with a 200
// response, which means the tool's auth gate must already let the
// request through (i.e. we're testing the post-auth flow). A future
// test could mock 401 to verify the unauth user UX.

import { test } from "@playwright/test";
import {
  mockAiRoute,
  uploadFixture,
  waitForToolReady,
  expect,
} from "./utils";

test.describe("/tool/ai-summarize", () => {
  test("renders mocked AI summary response", async ({ page }) => {
    const MOCK_SUMMARY = "This document is a test fixture used by the e2e suite.";

    // Mock BEFORE navigation — Playwright route handlers must be
    // installed before the request fires.
    await mockAiRoute(page, "summarize", {
      ok: true,
      summary: MOCK_SUMMARY,
      bulletPoints: [
        "Generated by tests/fixtures/generate.mjs",
        "One-page Helvetica fixture",
        "Author: pdfcraftai test suite",
      ],
      tokensUsed: 42,
      costMicros: 0,
    });

    // Auth gate — the live /api/ai/* routes require sign-in. The
    // mock doesn't care about cookies, but the server-rendered page
    // might gate the UI. If the test machine isn't signed in, the
    // page may render a sign-in CTA instead of the tool. Skip
    // gracefully when that's the case — Phase 2 will set up a
    // signed-in fixture.
    await page.goto("/tool/ai-summarize");
    const signedOut = await page
      .getByText(/sign in|log in/i)
      .first()
      .isVisible()
      .catch(() => false);
    test.skip(signedOut, "sign-in required; signed-in fixture is Phase 2");

    await waitForToolReady(page);
    await uploadFixture(page, "single-page.pdf");

    // CTA copy: typical AI tool primary is "Summarize" or "Run".
    await page
      .getByRole("button", { name: /summarize|run/i })
      .first()
      .click();

    // The mocked summary should render in the output card.
    await expect(page.getByText(MOCK_SUMMARY)).toBeVisible({
      timeout: 10_000,
    });
  });
});
